# Model Configuration
model:
  weights: "models/best.pt"
  confidence_threshold: 0.25
  iou_threshold: 0.45
  input_size: 960
  device: "cuda"  # or "cpu"

# Camera Configuration
camera:
  fov_horizontal: 82  # degrees
  fov_vertical: 65    # degrees
  image_width: 1920
  image_height: 1080

# Geolocation Settings
geolocation:
  earth_circumference: 40075000  # meters
  min_altitude: 5  # meters
  max_altitude: 200  # meters

# Alert System
alert:
  enabled: true
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  recipient_emails:
    - "rescue@example.com"
  
# Logging
logging:
  level: "INFO"
  save_to_file: true
  log_directory: "logs/"

# Processing
processing:
  save_annotated_video: true
  output_directory: "outputs/"
  frame_skip: 1  # Process every Nth frame
